# Generated by Django 2.1.1 on 2018-11-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Django_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_path', models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\sakodaken\\PycharmProjects')),
            ],
        ),
        migrations.CreateModel(
            name='Django_Project2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_path', models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\sakodaken\\PycharmProjects', recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='Django_Project3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_path', models.FilePathField(allow_folders=True, path='C:\\Users\\sakodaken\\PycharmProjects', recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='Django_Project4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_path', models.FilePathField(allow_folders=True, match='f*', path='C:\\Users\\sakodaken\\PycharmProjects', recursive=True)),
            ],
        ),
    ]
