# Generated by Django 2.1.1 on 2018-11-22 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_django_project5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='選手名')),
                ('votes', models.IntegerField(default=0, verbose_name='票数')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='チーム名')),
                ('pub_date', models.DateTimeField(verbose_name='作成日')),
            ],
        ),
        migrations.DeleteModel(
            name='Django_Project',
        ),
        migrations.DeleteModel(
            name='Django_Project2',
        ),
        migrations.DeleteModel(
            name='Django_Project3',
        ),
        migrations.DeleteModel(
            name='Django_Project4',
        ),
        migrations.DeleteModel(
            name='Django_Project5',
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teams', verbose_name='チーム名'),
        ),
    ]
