# Generated by Django 2.1.1 on 2018-11-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181101_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django_project4',
            name='project_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, match='f*', path='C:\\Users\\sakodaken\\PycharmProjects'),
        ),
    ]
