# Generated by Django 2.1.1 on 2018-10-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoproject',
            name='app0_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ0_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app1_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ1_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app2_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ2_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app3_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ3_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app4_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ4_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app5_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ5_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app6_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ6_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app7_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ7_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app8_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ8_URL'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app9_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ9_URL'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app0',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ0'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ1'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ2'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ3'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ4'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ5'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ6'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ7'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ8'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ9'),
        ),
    ]
