# Generated by Django 2.1.1 on 2018-10-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181010_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoproject',
            name='app0',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app0_URL',
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ10'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app10_URL',
            field=models.URLField(blank=True, null=True, verbose_name='アプリ10_URL'),
        ),
    ]
