# Generated by Django 2.1.1 on 2018-10-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181010_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoproject',
            name='app10_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL10'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app1_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL1'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app2_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL2'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app3_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL3'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app4_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL4'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app5_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL5'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app6_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL6'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app7_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL7'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app8_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL8'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app9_URL',
            field=models.URLField(blank=True, null=True, verbose_name='設定URL9'),
        ),
    ]
