# Generated by Django 2.1.1 on 2018-10-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181010_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoproject',
            name='app10',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app10_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app2',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app2_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app3',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app3_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app4',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app4_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app5',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app5_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app6',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app6_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app7',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app7_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app8',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app8_URL',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app9',
        ),
        migrations.RemoveField(
            model_name='djangoproject',
            name='app9_URL',
        ),
    ]
