# Generated by Django 2.1.1 on 2018-10-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181010_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoproject',
            name='app10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ10'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app10_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL10'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ2'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app2_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL2'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ3'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app3_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL3'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ4'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app4_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL4'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ5'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app5_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL5'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ6'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app6_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL6'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ7'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app7_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL7'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ8'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app8_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL8'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリ9'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app9_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL9'),
        ),
        migrations.AlterField(
            model_name='djangoproject',
            name='app1_URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL1'),
        ),
    ]
