# Generated by Django 2.1.1 on 2018-10-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181010_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoproject',
            name='app10_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ10', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app1_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ1', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app2_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ2', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app3_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ3', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app4_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ4', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app5_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ5', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app6_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ6', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app7_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ7', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app8_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ8', to='app.AppSpecie'),
        ),
        migrations.AddField(
            model_name='djangoproject',
            name='app9_specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='アプリ9', to='app.AppSpecie'),
        ),
        migrations.AlterField(
            model_name='appspecie',
            name='specie',
            field=models.CharField(max_length=255, unique=True, verbose_name='アプリの種類'),
        ),
    ]
