# Generated by Django 2.1.1 on 2018-10-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181015_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSpecie_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='アプリの必要情報の型')),
            ],
        ),
        migrations.RenameField(
            model_name='appspecie',
            old_name='specie',
            new_name='name',
        ),
        migrations.AddField(
            model_name='appspecie',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AppSpecie_type'),
        ),
    ]
