# Generated by Django 2.1.2 on 2018-11-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='チーム名')),
            ],
        ),
        migrations.RemoveField(
            model_name='baseballplayer',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='baseballplayer',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='baseballplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team', verbose_name='所属チーム'),
        ),
    ]
