# Generated by Django 2.1.1 on 2018-11-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_django_project5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_num', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Django_Project',
        ),
        migrations.DeleteModel(
            name='Django_Project2',
        ),
        migrations.DeleteModel(
            name='Django_Project3',
        ),
        migrations.DeleteModel(
            name='Django_Project4',
        ),
        migrations.DeleteModel(
            name='Django_Project5',
        ),
    ]
