# Generated by Django 2.1.1 on 2018-11-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181126_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inc',
            name='increment_num',
        ),
    ]
