# Generated by Django 2.1.1 on 2018-11-26 07:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_inc_increment_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='inc',
            name='increment_num',
            field=models.IntegerField(default=app.models.get_next),
        ),
    ]
