# Generated by Django 2.1.2 on 2018-11-28 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('gender', models.CharField(blank=True, choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別')),
                ('login', models.TimeField(choices=[(datetime.time(9, 0), '9時'), (datetime.time(10, 0), '10時'), (datetime.time(11, 0), '11時'), (datetime.time(12, 0), '12時'), (datetime.time(13, 0), '13時'), (datetime.time(14, 0), '14時'), (datetime.time(15, 0), '15時')], verbose_name='ログイン可能時間')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team', verbose_name='所属チーム'),
        ),
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.ManyToManyField(to='app.Title', verbose_name='過去タイトル'),
        ),
    ]
