# Generated by Django 2.1.2 on 2018-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='登録日時')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('team', models.CharField(max_length=255, verbose_name='所属チーム')),
                ('draft', models.CharField(max_length=255, verbose_name='ドラフト情報')),
                ('birth', models.DateField(verbose_name='生年月日')),
            ],
        ),
    ]
