print("/////////////Case1/////////////")
print("[注]空のリストはFalse")
print("------------program------------")
print("if not []:")
print("    print('[]はFalse')")
print("-----------結果----------------")
if not []:
 print("[]はFalse")
print("")
print("/////////////Case2/////////////")
print("[注]空の辞書はFalse")
print("------------program------------")
print("if not {}:")
print("    print('{}はFalse')")
print("-----------結果----------------")
if not {}:
 print("{}はFalse")
print("")
print("/////////////Case3/////////////")
print("[注]空の文字列はFalse")
print("------------program------------")
print("if not '':")
print("    print('""はFalse')")
print("-----------結果----------------")
if not '':
 print("''はFalse")
print("")
print("/////////////Case4/////////////")
print("[注]数字の0はFalse")
print("------------program------------")
print("if not 0:")
print("    print('0はFalse')")
print("-----------結果----------------")
if not 0:
 print("0はFalse")
print("/////////////Case5/////////////")
print("[注]数字の0.0はFalse")
print("------------program------------")
print("if not 0.0:")
print("    print('0.0はFalse')")
print("-----------結果----------------")
if not 0.0:
 print("0.0はFalse")
print("")
print("/////////////Case6/////////////")
print("[注]bool値で判定")
print("------------program------------")
print("print(bool([]))")
print("-----------結果----------------")
print(bool([]))
print("------------program------------")
print("print(bool({}))")
print("-----------結果----------------")
print(bool({}))
print("------------program------------")
print("print(bool(''))")
print("-----------結果----------------")
print(bool(''))
print("------------program------------")
print("print(bool(0))")
print("-----------結果----------------")
print(bool(0))
print("------------program------------")
print("print(bool(0.0))")
print("-----------結果----------------")
print(bool(0.0))
print("------------program------------")
print("print(bool(1.0))")
print("-----------結果----------------")
print(bool(1.0))
