# Generated by Django 2.1.1 on 2018-11-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_django_project5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='選手名')),
                ('team', models.CharField(choices=[('G', '巨人'), ('C', '広島'), ('S', 'ヤクルト'), ('De', '横浜'), ('D', '中日'), ('T', '阪神')], max_length=2, verbose_name='所属チーム')),
            ],
        ),
        migrations.DeleteModel(
            name='Django_Project',
        ),
        migrations.DeleteModel(
            name='Django_Project2',
        ),
        migrations.DeleteModel(
            name='Django_Project3',
        ),
        migrations.DeleteModel(
            name='Django_Project4',
        ),
        migrations.DeleteModel(
            name='Django_Project5',
        ),
    ]
