# Generated by Django 2.1.1 on 2018-11-26 03:54

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_django_project5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('File', models.FileField(upload_to=app.models.get_upload_to)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.DeleteModel(
            name='Django_Project',
        ),
        migrations.DeleteModel(
            name='Django_Project2',
        ),
        migrations.DeleteModel(
            name='Django_Project3',
        ),
        migrations.DeleteModel(
            name='Django_Project4',
        ),
        migrations.DeleteModel(
            name='Django_Project5',
        ),
    ]
