# Generated by Django 2.1.1 on 2018-11-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181101_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Django_Project5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_path', models.FilePathField(allow_files=False, allow_folders=True, match='fds', path='C:\\Users\\sakodaken\\PycharmProjects')),
            ],
        ),
    ]
