# Generated by Django 2.1.1 on 2018-11-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181101_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django_project2',
            name='project_path',
            field=models.FilePathField(path='C:\\Users\\sakodaken\\PycharmProjects'),
        ),
        migrations.AlterField(
            model_name='django_project3',
            name='project_path',
            field=models.FilePathField(allow_folders=True, path='C:\\Users\\sakodaken\\PycharmProjects'),
        ),
    ]
