# Generated by Django 2.1.1 on 2018-10-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallcategoryname', models.CharField(max_length=200, verbose_name='中カテゴリー名')),
                ('middlecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_example.MiddleCategory', verbose_name='中カテゴリー')),
            ],
        ),
    ]
